---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/laravel/
    - export DEPLOYPUBLICPATH=/home/$USER/public_html/
    - /bin/cp -R laravel/* $DEPLOYPATH
    - /bin/cp -R public_html/* $DEPLOYPUBLICPATH
    - cd $DEPLOYPATH && composer install --optimize-autoloader --no-dev; php artisan config:cache; php artisan route:cache; php artisan view:cache;